const roles = {
    /*
    'Role Name': <Minimal Level To Obtain this Role>
    */
    'Bronze V': 0,
    'Bronze IV': 5,
    'Bronze III': 10,
    'Bronze II': 15,
    'Bronze I': 20,
    'Elite V': 25,
    'Elite IV': 30,
    'Elite III': 35,
    'Elite II': 40,
    'Elite I': 45,
    'Master V': 50,
    'Master IV': 55,
    'Master III': 60,
    'Master II': 65,
    'Master I': 70,
    'Grand Master V': 75,
    'Grand Master IV': 80,
    'Grand Master III': 85,
    'Grand Master II': 90,
    'Grand Master I': 95,
    'Epic V': 100,
    'Epic IV': 105,
    'Epic III': 110,
    'Epic II': 115,
    'Epic I': 120,
    'Legend V': 125,
    'Legend IV': 130,
    'Legend III': 135,
    'Legend II': 140,
    'Legend I': 145,
    'Mythic V': 150,
    'Mythic IV': 155,
    'Mythic III': 160,
    'Mythic II': 165,
    'Mythic I': 170,
    'Mythic Glory': 175,
    'EMERALD V': 180,
    'EMERALD IV': 185,
    'EMERALD III': 190,
    'EMERALD II': 195,
    'EMERALD I': 200,
    'THE EMERALD V': 205,
    'THE EMERALD IV': 210,
    'THE EMERALD III': 215,
    'THE EMERALD II': 220,
    'THE EMERALD II': 225,
    'THE LEGEND BRONZE V': 230,
    'THE LEGEND BRONZE IV': 235,
    'THE LEGEND BRONZE III': 240,
    'THE LEGEND BRONZE II': 245,
    'THE LEGEND BRONZE I': 250,
    'THE LEGEND ELITE IV': 255,
    'THE LEGEND ELITE V': 260,
    'THE LEGEND ELITE III': 265,
    'THE LEGEND ELITE II': 270,
    'THE LEGEND ELITE I': 275,
    'THE LEGEND MASTER V': 280,
    'THE LEGEND MASTER IV': 285,
    'THE LEGEND MASTER III': 290,
    'THE LEGEND MASTER II': 295,
    'THE LEGEND MASTER I': 300,
    'LEGENDARY V': 310,
    'LEGENDARY IV': 315,
    'LEGENDARY III': 320,
    'LEGENDARY II': 325,
    'LEGENDARY I': 330,
    'KING ALL ROLE V': 335,
    'KING ALL ROLE IV': 340,
    'KING ALL ROLE III': 345,
    'KING ALL ROLE II': 350,
    'KING ALL ROLE II': 355,
    'KING ALL ROLE I': 340,
    'THE LEGEND KING ALL ROLE': 350,
    'HACKER': 1000,
    'INFINITY ROLE': 5000,
    
}

export function before(m) {
        let user = db.data.users[m.sender]
        let level = user.level
        let role = (Object.entries(roles).sort((a, b) => b[1] - a[1]).find(([, minLevel]) => level >= minLevel) || Object.entries(roles)[0])[0]
        user.role = role
        return !0
    
}